---
name: DIREGAPIC Updater
on:  # yamllint disable-line rule:truthy
  schedule:
  - cron: '19 */8 * * *'
  workflow_dispatch:

jobs:
  regenerate-compute:
    if: github.repository == 'googleapis/googleapis'
    runs-on: ubuntu-latest
    container: gcr.io/gapic-images/googleapis:prod
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Download discovery docs
      run: |
        curl https://raw.githubusercontent.com/googleapis/discovery-artifact-manager/refs/heads/master/discoveries/compute.v1.json --output google/cloud/compute/v1/compute.v1.json
        echo compute_revision=$(grep -oP '"revision":\s*"\d+"' google/cloud/compute/v1/compute.v1.json | grep -oP '\d+') >> $GITHUB_ENV
        echo == compute_revision=$(grep -oP '"revision":\s*"\d+"' google/cloud/compute/v1/compute.v1.json | grep -oP '\d+')
        echo == github_env: $GITHUB_ENV : $(cat $GITHUB_ENV)
        echo "----"
    - name: Regenerate API definitions
      run: |
        git config --global --add safe.directory /__w/googleapis/googleapis
        bazelisk build --experimental_convenience_symlinks=normal //google/cloud/compute/v1:compute_gen
        cp bazel-bin/google/cloud/compute/v1/compute_gen.proto google/cloud/compute/v1/compute.proto
        cp bazel-bin/google/cloud/compute/v1/compute_gen.config.out.json google/cloud/compute/v1/compute.config.json
        bazelisk build --experimental_convenience_symlinks=normal //google/cloud/compute/v1:compute_grpc_service_config_gen
        cp bazel-bin/google/cloud/compute/v1/compute_grpc_service_config_gen.json google/cloud/compute/v1/compute_grpc_service_config.json
        bazelisk build --experimental_convenience_symlinks=normal //google/cloud/compute/v1:compute_gapic_gen
        cp bazel-bin/google/cloud/compute/v1/compute_gapic_gen.yaml google/cloud/compute/v1/compute_gapic.yaml
        # DO NOT MERGE: This needs to be submitted to the Google-internal SoT
        echo api_changes=$( { git diff-index HEAD | grep -v compute.config.json &> /dev/null ; } && git diff-index --shortstat HEAD) >> $GITHUB_ENV
        echo "Diff index:"
        git diff-index HEAD
        echo "Diff index, filtered:"
        git diff-index HEAD | grep -v compute.config.json
        echo == Code: $?
        echo == computed api_changes: $( { git diff-index HEAD | grep -v compute.config.json &> /dev/null ; } && git diff-index --shortstat HEAD)
        echo == github_env: $GITHUB_ENV : $(cat $GITHUB_ENV)
        echo "----"
        echo === git diff
        git diff
    - name: Build GAPIC clients
      if: contains(env.api_changes, 'file')
      run: |
        echo "Would Build"
    - name: Create PR
      if: contains(env.api_changes, 'file')
      run: |
        echo "Would create PR"
